const canvas=document.getElementById("board"),ctx=canvas.getContext("2d");
const screens={home:document.getElementById("homeScreen"),game:document.getElementById("gameScreen"),result:document.getElementById("resultScreen")};
const scoreEl=document.getElementById("score"),turnEl=document.getElementById("turnScore"),dartEl=document.getElementById("dartCount"),modeEl=document.getElementById("modeLabel"),lastEl=document.getElementById("lastThrow"),hintEl=document.getElementById("hint"),badge=document.getElementById("hitBadge");
const state={mode:"501",score:501,turn:0,darts:[],totalDarts:0,bestRound:0,oneEighty:0,drag:false,start:null,sound:true};let audioCtx;
const C=210,sectors=[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5];
function show(n){Object.values(screens).forEach(x=>x.classList.remove("active"));screens[n].classList.add("active")}
function loadRecords(){const r=JSON.parse(localStorage.getItem("cuteDartRecords")||"{}");document.getElementById("bestRoundHome").textContent=r.bestRound||0;document.getElementById("oneEightyHome").textContent=r.oneEighty||0}
function saveRecords(){const r=JSON.parse(localStorage.getItem("cuteDartRecords")||"{}");r.bestRound=Math.max(r.bestRound||0,state.bestRound);r.oneEighty=(r.oneEighty||0)+state.oneEighty;localStorage.setItem("cuteDartRecords",JSON.stringify(r));loadRecords()}
function beep(freq=500){if(!state.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.value=.04;o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.07)}catch{}}
function drawBoard(){const d=devicePixelRatio||1;canvas.width=420*d;canvas.height=420*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,420,420);const rings=[198,181,151,140,94,82,18],fills=["#79c98d","#f6f2e9","#ef737e","#fff6df","#79c98d","#ef737e","#ffd85e"];ctx.beginPath();ctx.arc(C,C,198,0,Math.PI*2);ctx.fillStyle="#fff";ctx.fill();for(let i=0;i<6;i++){ctx.beginPath();ctx.arc(C,C,rings[i],0,Math.PI*2);ctx.fillStyle=fills[i];ctx.fill()}for(let i=0;i<20;i++){const a=-Math.PI/2+i*Math.PI*2/20,a2=a+Math.PI*2/20;ctx.beginPath();ctx.moveTo(C,C);ctx.arc(C,C,198,a,a2);ctx.closePath();ctx.fillStyle=i%2?"#fff6df":"#315a91";ctx.globalAlpha=.14;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle="rgba(49,90,145,.35)";ctx.stroke()}[198,181,151,140,94,82].forEach(r=>{ctx.beginPath();ctx.arc(C,C,r,0,Math.PI*2);ctx.strokeStyle="#315a91";ctx.lineWidth=2;ctx.stroke()});ctx.fillStyle="#315a91";ctx.font="bold 16px Trebuchet MS";ctx.textAlign="center";ctx.textBaseline="middle";for(let i=0;i<20;i++){const a=-Math.PI/2+(i+.5)*Math.PI*2/20;ctx.fillText(sectors[i],C+166*Math.cos(a),C+166*Math.sin(a))}ctx.beginPath();ctx.arc(C,C,18,0,Math.PI*2);ctx.fillStyle="#ffd85e";ctx.fill();ctx.strokeStyle="#315a91";ctx.stroke()}
function pos(e){const r=canvas.getBoundingClientRect(),s=420/r.width;return{x:(e.clientX-r.left)*s,y:(e.clientY-r.top)*s}}
function hitScore(x,y){const dx=x-C,dy=y-C,dist=Math.hypot(dx,dy);if(dist>198)return{score:0,label:"MISS",kind:"miss"};if(dist<=18)return{score:50,label:"BULL",kind:"bull"};if(dist<=82)return{score:25,label:"25",kind:"outerbull"};const angle=(Math.atan2(dy,dx)+Math.PI/2+Math.PI*2)%(Math.PI*2),idx=Math.floor(angle/(Math.PI*2/20)),n=sectors[idx];if(dist<=94)return{score:n*3,label:"T"+n,kind:"triple"};if(dist<=140)return{score:n,label:String(n),kind:"single"};if(dist<=151)return{score:n*2,label:"D"+n,kind:"double"};return{score:n,label:String(n),kind:"single"}}
function update(){scoreEl.textContent=state.score;turnEl.textContent=state.turn;dartEl.textContent=state.darts.length+" / 3 鏢"}
function newGame(mode){state.mode=mode;state.score=mode==="practice"?0:Number(mode);state.turn=0;state.darts=[];state.totalDarts=0;state.bestRound=0;state.oneEighty=0;modeEl.textContent=mode==="practice"?"練習":mode;lastEl.textContent="準備好了嗎？";hintEl.textContent="👆 按住靶面，往外拉再放開！";update();drawBoard();show("game")}
function finishTurn(){if(!state.darts.length)return;state.bestRound=Math.max(state.bestRound,state.turn);if(state.turn===180)state.oneEighty++;state.darts=[];state.turn=0;update();lastEl.textContent="✨ 新回合！";hintEl.textContent="再丟三鏢吧！";document.getElementById("endTurnBtn").disabled=true}
function finishGame(){saveRecords();document.getElementById("finalDarts").textContent=state.totalDarts;document.getElementById("finalBest").textContent=state.bestRound;document.getElementById("final180").textContent=state.oneEighty;document.getElementById("resultTitle").textContent=state.mode==="practice"?"練習完成！":"太棒啦！";document.getElementById("resultSub").textContent=state.mode==="practice"?"今天也有好好練習喔 ✨":"恭喜你完成這一局！";show("result")}
function throwDart(p){const h=hitScore(p.x,p.y);let gained=h.score;if(state.mode!=="practice"){const next=state.score-gained;if(next<0||next===1){h.label="BUST";gained=0}else state.score=next}else state.score+=gained;state.turn+=gained;state.totalDarts++;state.darts.push(h);beep(h.kind==="miss"?180:700);lastEl.textContent=h.label==="BUST"?"💥 BUST！":h.score?"🎯 "+h.label+" +"+h.score:"💨 MISS！";badge.textContent=h.label==="BUST"?"BUST":h.label+(h.score?"!":"");badge.classList.remove("show");void badge.offsetWidth;badge.classList.add("show");update();document.getElementById("endTurnBtn").disabled=false;if(state.mode!=="practice"&&state.score===0){setTimeout(finishGame,650);return}if(state.darts.length>=3)setTimeout(finishTurn,700)}
canvas.addEventListener("pointerdown",e=>{e.preventDefault();state.drag=true;state.start=pos(e);canvas.setPointerCapture(e.pointerId);hintEl.textContent="↗ 調整方向與力道，放開！"});
canvas.addEventListener("pointerup",e=>{if(!state.drag)return;state.drag=false;const p=pos(e),dx=p.x-state.start.x,dy=p.y-state.start.y,len=Math.hypot(dx,dy);let tx=C+dx*.55,ty=C+dy*.55;if(len<12){tx=p.x;ty=p.y}tx=Math.max(2,Math.min(418,tx));ty=Math.max(2,Math.min(418,ty));throwDart({x:tx,y:ty});hintEl.textContent="👆 按住靶面，往外拉再放開！"});
canvas.addEventListener("pointercancel",()=>state.drag=false);
document.querySelectorAll(".mode-card").forEach(b=>b.addEventListener("click",()=>newGame(b.dataset.mode)));
document.getElementById("restartBtn").addEventListener("click",()=>newGame(state.mode));document.getElementById("endTurnBtn").addEventListener("click",finishTurn);document.getElementById("againBtn").addEventListener("click",()=>newGame(state.mode));document.getElementById("homeBtn").addEventListener("click",()=>{loadRecords();show("home")});document.getElementById("soundBtn").addEventListener("click",()=>{state.sound=!state.sound;document.getElementById("soundBtn").textContent=state.sound?"🔊":"🔇"});loadRecords();drawBoard();