/* Local multiplayer character-select layer for Gesture Dart */
(() => {
  const home=document.getElementById("homeScreen"),grid=home?.querySelector(".play-style-grid"),stage=document.getElementById("cameraStage");
  if(!home||!grid||!stage)return;

  const CHARS=[
    {id:"sparky",name:"Sparky",role:"電氣小萌獸",icon:"⚡",color:"#ffd84d",avatar:"⚡"},
    {id:"kai",name:"Kai",role:"疾風射手",icon:"🎯",color:"#58c7ef",avatar:"🧑🏻"},
    {id:"hina",name:"Hina",role:"熱血飛鏢手",icon:"🔥",color:"#ff8d66",avatar:"👧🏻"},
    {id:"rin",name:"Rin",role:"森林守護者",icon:"🌿",color:"#8fdc9c",avatar:"🧑🏼"}
  ];
  const style=document.createElement("style");style.textContent=`
    .play-style-card.multi-entry{background:linear-gradient(145deg,#fff2bd,#dff6ff)}
    .multi-setup{display:none;margin:12px 0 14px;padding:16px;border:4px solid #fff;border-radius:24px;background:rgba(255,248,232,.97);box-shadow:var(--shadow)}.multi-setup.open{display:block}.multi-setup h3{margin:0 0 12px;text-align:center;color:var(--dark);font-size:22px}.multi-row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:10px 0}.multi-stepper,.multi-modes{display:flex;gap:7px}.multi-stepper button,.multi-modes button{border:2px solid #fff;border-radius:12px;background:#e8f7ff;color:var(--dark);font-weight:1000;min-width:44px;min-height:40px;box-shadow:0 3px 0 rgba(41,51,74,.12)}.multi-modes button.active{background:var(--yellow)}
    .character-pick-title{margin:14px 0 8px;font-weight:1000;text-align:center;color:var(--dark)}.character-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.character-card{position:relative;border:3px solid #fff;border-radius:18px;background:#fff;padding:10px 8px;text-align:center;box-shadow:0 5px 0 rgba(41,51,74,.1);cursor:pointer;transition:.15s}.character-card:hover{transform:translateY(-2px)}.character-card.selected{outline:4px solid var(--char);transform:scale(1.03)}.character-card.used{opacity:.36;filter:grayscale(.65);pointer-events:none}.character-avatar{display:grid;place-items:center;width:72px;height:72px;margin:0 auto 6px;border-radius:22px;background:linear-gradient(145deg,#fff,var(--char));font-size:38px;border:3px solid rgba(255,255,255,.9)}.character-card b{display:block;font-size:17px}.character-card small{display:block;margin-top:3px}.seat-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:10px 0}.seat{padding:8px;border-radius:12px;background:#edf4f7;text-align:center;font-weight:900}.seat.filled{background:var(--seat);color:#24364b}.seat.active-pick{outline:3px solid #58c7ef}
    .multi-player-board{display:none;position:absolute;z-index:17;left:max(10px,env(safe-area-inset-left));top:50%;transform:translateY(-50%);width:148px;padding:10px;border:2px solid rgba(255,255,255,.45);border-radius:20px;background:rgba(20,35,52,.42);backdrop-filter:blur(5px);color:#fff;pointer-events:none}.camera-screen.throwing.multiplayer-active .multi-player-board{display:block}.multi-player{display:grid;grid-template-columns:36px 1fr;gap:7px;align-items:center;padding:8px 7px;margin:6px 0;border-radius:12px;background:rgba(255,255,255,.12);font-weight:900;opacity:.7}.multi-player.active{outline:3px solid var(--pc);background:rgba(255,255,255,.2);opacity:1;transform:scale(1.04)}.multi-player .avatar{font-size:24px}.multi-player span{display:block;font-size:12px}.multi-player strong{display:block;font-size:21px}.multi-turn-banner{display:none;position:absolute;z-index:40;left:50%;top:52%;transform:translate(-50%,-50%);min-width:58%;padding:18px 24px;border-radius:26px;background:rgba(20,35,52,.86);border:4px solid #fff;color:#fff;text-align:center;font-size:clamp(30px,9vw,58px);font-weight:1000;text-shadow:0 3px 0 rgba(0,0,0,.35);pointer-events:none}.multi-turn-banner.show{display:block;animation:multiPop 1.8s ease both}@keyframes multiPop{0%{opacity:0;transform:translate(-50%,-50%) scale(.7)}15%{opacity:1;transform:translate(-50%,-50%) scale(1.05)}75%{opacity:1}100%{opacity:0;transform:translate(-50%,-50%) scale(.98)}}
    @media(max-width:700px){.character-grid{grid-template-columns:1fr 1fr}.seat-strip{grid-template-columns:1fr 1fr}}@media(max-width:430px){.multi-player-board{left:6px;width:112px;padding:7px}.multi-player{grid-template-columns:28px 1fr;padding:6px 4px}.multi-player strong{font-size:18px}.multi-player span{font-size:10px}}
  `;document.head.appendChild(style);

  const entry=document.createElement("button");entry.id="multiplayerEntry";entry.className="play-style-card multi-entry";entry.innerHTML='<span>👥</span><b>多人 Gesture Dart</b><small>2～4 人選角輪流體感投鏢</small>';grid.appendChild(entry);
  const setup=document.createElement("div");setup.className="multi-setup";setup.innerHTML=`<h3>👥 多人對戰設定</h3><div class="multi-row"><label>玩家人數</label><div class="multi-stepper"><button id="multiMinus">−</button><b id="multiCount">2</b><button id="multiPlus">＋</button></div></div><div class="multi-row"><label>遊戲分數</label><div class="multi-modes"><button class="active" data-score="301">301</button><button data-score="501">501</button></div></div><div class="character-pick-title" id="pickTitle">玩家 1 選角</div><div id="characterGrid" class="character-grid"></div><div id="seatStrip" class="seat-strip"></div><button id="multiStart" class="primary-btn" disabled>完成選角後開始 🎯</button>`;grid.after(setup);
  const board=document.createElement("div");board.className="multi-player-board";board.innerHTML='<b>角色分數</b><div id="multiPlayerList"></div>';stage.appendChild(board);const banner=document.createElement("div");banner.className="multi-turn-banner";stage.appendChild(banner);

  let count=2,startScore=301,active=false,current=0,turnDarts=0,locked=false,players=[],picks=[];
  const countEl=setup.querySelector("#multiCount"),charGrid=setup.querySelector("#characterGrid"),seatStrip=setup.querySelector("#seatStrip"),pickTitle=setup.querySelector("#pickTitle"),startBtn=setup.querySelector("#multiStart"),list=board.querySelector("#multiPlayerList");
  function renderSetup(){countEl.textContent=count;picks=picks.slice(0,count);while(picks.length<count)picks.push(null);const next=picks.findIndex(x=>!x);pickTitle.textContent=next>=0?`玩家 ${next+1} 選角`:`選角完成`;charGrid.innerHTML="";CHARS.forEach(ch=>{const used=picks.some(p=>p?.id===ch.id);const el=document.createElement("button");el.className="character-card"+(used?" used":"");el.style.setProperty("--char",ch.color);el.innerHTML=`<div class="character-avatar">${ch.avatar}</div><b>${ch.name}</b><small>${ch.icon} ${ch.role}</small>`;el.onclick=()=>{const idx=picks.findIndex(x=>!x);if(idx<0||used)return;picks[idx]=ch;renderSetup()};charGrid.appendChild(el)});seatStrip.innerHTML="";for(let i=0;i<count;i++){const ch=picks[i],s=document.createElement("div");s.className="seat"+(ch?" filled":"")+(i===next?" active-pick":"");if(ch)s.style.setProperty("--seat",ch.color);s.textContent=ch?`${ch.icon} ${ch.name}`:`玩家 ${i+1}`;s.onclick=()=>{if(ch){picks[i]=null;for(let j=i+1;j<picks.length;j++){if(!picks[j-1]&&picks[j]){picks[j-1]=picks[j];picks[j]=null}}renderSetup()}};seatStrip.appendChild(s)}startBtn.disabled=picks.some(x=>!x);startBtn.textContent=startBtn.disabled?"完成選角後開始 🎯":"開始多人對戰 🎯"}
  function renderPlayers(){list.innerHTML="";players.forEach((p,i)=>{const el=document.createElement("div");el.className="multi-player"+(i===current?" active":"");el.style.setProperty("--pc",p.character.color);el.innerHTML=`<div class="avatar">${p.character.avatar}</div><div><span>${p.character.name}</span><strong>${p.score}</strong></div>`;list.appendChild(el)});if(active){cameraScore.textContent=`${players[current].character.name}｜${players[current].score} 分`;cameraDarts.textContent=`${turnDarts} / 3 鏢`}}
  function showBanner(text){banner.textContent=text;banner.classList.remove("show");void banner.offsetWidth;banner.classList.add("show")}
  function nextPlayer(){if(!active)return;current=(current+1)%players.length;turnDarts=0;locked=false;cameraState.darts=0;cameraState.marks=[];drawCameraBoard();renderPlayers();showBanner(`🎯 ${players[current].character.name} 回合`)}
  function finishMultiplayer(winner){locked=true;showBanner(`🏆 ${winner.character.name} WIN！`);setTimeout(()=>{active=false;cameraScreen.classList.remove("multiplayer-active");cameraThrowing=false;cameraScreen.classList.remove("throwing");if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});stopCamera();show("home");setup.classList.add("open")},4200)}

  renderSetup();entry.onclick=()=>setup.classList.toggle("open");setup.querySelector("#multiMinus").onclick=()=>{count=Math.max(2,count-1);renderSetup()};setup.querySelector("#multiPlus").onclick=()=>{count=Math.min(4,count+1);renderSetup()};setup.querySelectorAll(".multi-modes button").forEach(btn=>btn.onclick=()=>{setup.querySelectorAll(".multi-modes button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");startScore=Number(btn.dataset.score)});
  startBtn.onclick=()=>{players=picks.slice(0,count).map(ch=>({character:ch,score:startScore}));current=0;turnDarts=0;locked=false;active=true;startCameraMode();cameraScreen.classList.add("multiplayer-active");renderPlayers();showBanner(`🎯 ${players[0].character.name} 先攻`);setup.classList.remove("open")};

  const baseCameraThrow=cameraThrow;cameraThrow=function(p){if(!active){baseCameraThrow(p);return}if(locked)return;const hit=hitScore(p.x,p.y),player=players[current];baseCameraThrow(p);turnDarts++;const next=player.score-hit.score;if(next<0||next===1){cameraBadge.textContent="BUST"}else player.score=next;renderPlayers();const hold=Number(window.cuteDartResultHoldMs)||5000;if(player.score===0){setTimeout(()=>finishMultiplayer(player),Math.min(hold,10000));return}if(turnDarts>=3){locked=true;setTimeout(()=>{showBanner(`↪ 換 ${players[(current+1)%players.length].character.name}`);setTimeout(nextPlayer,1500)},hold)}};
  document.getElementById("cameraEntry")?.addEventListener("click",()=>{active=false;cameraScreen.classList.remove("multiplayer-active")},{capture:true});
})();